# Define workflow name
name: main

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - main
        
jobs:
  build:
    # This job will run on windows virtual machine
    runs-on: windows-latest

    steps:
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '3.3.7' # version of flutter
    
    # Get flutter dependencies.
    - run: flutter clean
    - run: flutter pub get
    
    # Build apk.
    - run: flutter build apk --release
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v1
      with:
        name: app-release # want to set current date time over here
        path: build/app/outputs/flutter-apk/app-release.apk
